# fly.toml app configuration file generated for splashcat-image-render on 2023-06-14T03:40:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "splashcat-image-render"
primary_region = "iad"
swap_size_mb = 1024

[env]
  PORT = "3000"

[processes]
  app = "run -A ./main.ts"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.image-render-check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/image-render/battle/2/render.png?test=1"
    port = 3000
    timeout = "10s"
    type = "http"